# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  new-from-rev: 0a83dd61fb818fa4a5a26f66d18befc6b2d248d1
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: linker/pathkey_unsafe.go
      linters: [ gosec ]
      text: G103
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goimports
    - gocritic
    - gofumpt
linters-settings:
  gosec:
    excludes: [ G304 ]
  gocritic:
    disabled-tags:
      - style
      - experimental
      - opinionated
    enabled-tags:
      - diagnostic
      - performance
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: false
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 50
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
