on:
  push:
  workflow_dispatch:
name: ci
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.17.x
      - run: go test -race -cover ./...
